#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter="$1"

echo "$script_dir -- $filter"

cd $script_dir
# find executables from inside the ./runs dir (-L to resolve potential symlinks) 
scripts=$(find -L ./runs -maxdepth 1 -mindepth 1 -perm +0111 -type f)

for script in $scripts; do
    if echo "$script" | grep -qv "$filter"; then # if the script name does not contain the filter
        echo "filtering $script"
        continue
    fi

    ./$script
done
